### ISSUE TITLE
Authy Desktop fails to install

### ISSUE THREAD

**Issue by fleish** [Installomator/Installomator#309]
Here is the output of the script:

```
2021-11-08 11:42:44 authydesktop ################## Start Installomator v. 0.7.0
2021-11-08 11:42:44 authydesktop ################## authydesktop
2021-11-08 11:42:44 authydesktop BLOCKING_PROCESS_ACTION=tell_user
2021-11-08 11:42:44 authydesktop NOTIFY=success
2021-11-08 11:42:44 authydesktop LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2021-11-08 11:42:44 authydesktop no blocking processes defined, using Authy Desktop as default
2021-11-08 11:42:44 authydesktop Changing directory to /Library/Application Support/JAMF/tmp
2021-11-08 11:42:45 authydesktop App(s) found: 
2021-11-08 11:42:45 authydesktop could not find Authy Desktop.app
2021-11-08 11:42:45 authydesktop appversion: 
2021-11-08 11:42:45 authydesktop Latest version of Authy Desktop is 1.9.0
2021-11-08 11:42:45 authydesktop Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg
2021-11-08 11:42:45 authydesktop error downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy
2021-11-08 11:42:45 authydesktop DEBUG mode, not reopening anything
2021-11-08 11:42:45 authydesktop ################## End Installomator, exit code 2 
```

I suspect this is due to the download URL issuing a 302 redirect to Location: https://s3.amazonaws.com/authy-electron-repository-production/authy/stable/1.9.0/darwin/x64/Authy%20Desktop-1.9.0.dmg for this particular version

**Comment by Theile** [comment]
This has already been fixed in our dev branch:
```
% /Users/st/Documents/GitHub/Installomator/utils/assemble.sh -r authydesktop
2021-11-08 21:40:14 authydesktop ################## Start Installomator v. 0.8.0
2021-11-08 21:40:14 authydesktop ################## authydesktop
2021-11-08 21:40:16 authydesktop BLOCKING_PROCESS_ACTION=tell_user
2021-11-08 21:40:16 authydesktop NOTIFY=success
2021-11-08 21:40:16 authydesktop LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2021-11-08 21:40:16 authydesktop no blocking processes defined, using Authy Desktop as default
2021-11-08 21:40:16 authydesktop Changing directory to /Users/st/Documents/GitHub/Installomator/build
2021-11-08 21:40:16 authydesktop App(s) found: 
2021-11-08 21:40:16 authydesktop could not find Authy Desktop.app
2021-11-08 21:40:16 authydesktop appversion: 
2021-11-08 21:40:16 authydesktop Latest version of Authy Desktop is 1.9.0
2021-11-08 21:40:16 authydesktop Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg
2021-11-08 21:40:23 authydesktop DEBUG mode, not checking for blocking processes
2021-11-08 21:40:23 authydesktop Installing Authy Desktop
2021-11-08 21:40:23 authydesktop Mounting /Users/st/Documents/GitHub/Installomator/build/Authy Desktop.dmg
2021-11-08 21:40:25 authydesktop Mounted: /Volumes/Authy Desktop 1.9.0
2021-11-08 21:40:25 authydesktop Verifying: /Volumes/Authy Desktop 1.9.0/Authy Desktop.app
2021-11-08 21:40:27 authydesktop Team ID matching: 9EVH78F4V4 (expected: 9EVH78F4V4 )
2021-11-08 21:40:27 authydesktop Downloaded version of Authy Desktop is 1.9.0 (replacing version ).
2021-11-08 21:40:27 authydesktop DEBUG enabled, skipping remove, copy and chown steps
2021-11-08 21:40:27 authydesktop Finishing…
2021-11-08 21:40:37 authydesktop App(s) found: 
2021-11-08 21:40:37 authydesktop could not find Authy Desktop.app
2021-11-08 21:40:37 authydesktop Installed Authy Desktop
2021-11-08 21:40:37 authydesktop notifying
2021-11-08 21:40:37 authydesktop Unmounting /Volumes/Authy Desktop 1.9.0
"disk4" ejected.
2021-11-08 21:40:37 authydesktop DEBUG mode, not reopening anything
2021-11-08 21:40:37 authydesktop ################## End Installomator, exit code 0 
```

**Comment by fleish** [comment]
@Theile thanks, can I get a commit ID for the fix and presumably a push to remote as I'm still seeing it broken in the dev branch I pulled from?

**Comment by Theile** [comment]
I can see you hit the Intel download, and that even downloads on my iPhone. (I just pasted the URL to Safari). 

I think you have another problem, maybe the script cannot write where you run it from, could you try with DEBUG=0?

**Comment by fleish** [comment]
Still no luck, it's ending up with a null downloadURL:

`+./Installomator.sh:1147> name='Authy Desktop'
+./Installomator.sh:1148> type=dmg
+./Installomator.sh:1149> downloadURL=+./Installomator.sh:1149> curl -L --silent --fail 'https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy'
+./Installomator.sh:1149> downloadURL=''
+./Installomator.sh:1150> appNewVersion=+./Installomator.sh:1150> curl -sfL --output /dev/null -r 0-0 '' --remote-header-name --remote-name -w '%{url_effective}\n'
+./Installomator.sh:1150> appNewVersion=+./Installomator.sh:1150> grep -o -E '([a-zA-Z0-9\_.%-]*)\.(dmg|pkg|zip|tbz)$'
+./Installomator.sh:1150> appNewVersion=+./Installomator.sh:1150> sed -E 's/.*-([0-9.]*)\.dmg/\1/g'
+./Installomator.sh:1150> appNewVersion=''
+./Installomator.sh:1151> expectedTeamID=9EVH78F4V4
+./Installomator.sh:3645> printlog 'BLOCKING_PROCESS_ACTION=tell_user'


...

+./Installomator.sh:3808> curl --location --fail --silent '' -o 'Authy Desktop.dmg'
+./Installomator.sh:3809> printlog 'error downloading '
`

**Comment by fleish** [comment]
@Theile just checking back on this to make sure you saw my last update since this was already closed

**Comment by Theile** [comment]
When I mention our dev-branch, that is the main page here: [GitHub.com/Installomator/Installomator](https://gitHub.com/Installomator/Installomator)

I have tested the label again, and not only can I paste the download URL into Safari at have it download the software (that currently looks only to be available for Intel), I can also test the script like this:
```
% GitHub/Installomator/utils/assemble.sh -r authydesktop
2021-11-16 08:46:23 authydesktop ################## Start Installomator v. 0.8.0
2021-11-16 08:46:23 authydesktop ################## authydesktop
2021-11-16 08:46:24 authydesktop BLOCKING_PROCESS_ACTION=tell_user
2021-11-16 08:46:24 authydesktop NOTIFY=success
2021-11-16 08:46:24 authydesktop LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2021-11-16 08:46:24 authydesktop no blocking processes defined, using Authy Desktop as default
2021-11-16 08:46:24 authydesktop Changing directory to /Users/st/Documents/GitHub/Installomator/build
2021-11-16 08:46:24 authydesktop App(s) found: 
2021-11-16 08:46:24 authydesktop could not find Authy Desktop.app
2021-11-16 08:46:24 authydesktop appversion: 
2021-11-16 08:46:24 authydesktop Latest version of Authy Desktop is 1.9.0
2021-11-16 08:46:24 authydesktop Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg
2021-11-16 08:46:29 authydesktop DEBUG mode, not checking for blocking processes
2021-11-16 08:46:29 authydesktop Installing Authy Desktop
2021-11-16 08:46:29 authydesktop Mounting /Users/st/Documents/GitHub/Installomator/build/Authy Desktop.dmg
2021-11-16 08:46:34 authydesktop Mounted: /Volumes/Authy Desktop 1.9.0
2021-11-16 08:46:34 authydesktop Verifying: /Volumes/Authy Desktop 1.9.0/Authy Desktop.app
2021-11-16 08:46:35 authydesktop Team ID matching: 9EVH78F4V4 (expected: 9EVH78F4V4 )
2021-11-16 08:46:35 authydesktop Downloaded version of Authy Desktop is 1.9.0 (replacing version ).
2021-11-16 08:46:35 authydesktop DEBUG enabled, skipping remove, copy and chown steps
2021-11-16 08:46:35 authydesktop Finishing…
2021-11-16 08:46:46 authydesktop App(s) found: 
2021-11-16 08:46:46 authydesktop could not find Authy Desktop.app
2021-11-16 08:46:46 authydesktop Installed Authy Desktop
2021-11-16 08:46:46 authydesktop notifying
2021-11-16 08:46:46 authydesktop Unmounting /Volumes/Authy Desktop 1.9.0
"disk6" ejected.
2021-11-16 08:46:46 authydesktop DEBUG mode, not reopening anything
2021-11-16 08:46:46 authydesktop ################## End Installomator, exit code 0 
```

The label I refer to here is in the fragments folder, so this one:
[Github.com/Installomator/Installomator/blob/dev/fragments/labels/authydesktop.sh](https://github.com/Installomator/Installomator/blob/dev/fragments/labels/authydesktop.sh)

**Comment by fleish** [comment]
@Theile OK, I now see your assemble script is building a new version (0.8.0). However, even when I try to run the resulting script that builds I am still seeing errors downloading on my systems:

```
./Installomator.sh authydesktop
2021-11-16 10:00:52 authydesktop ################## Start Installomator v. 0.8.0
2021-11-16 10:00:52 authydesktop ################## authydesktop
2021-11-16 10:00:53 authydesktop BLOCKING_PROCESS_ACTION=tell_user
2021-11-16 10:00:53 authydesktop NOTIFY=success
2021-11-16 10:00:53 authydesktop LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2021-11-16 10:00:53 authydesktop no blocking processes defined, using Authy Desktop as default
2021-11-16 10:00:53 authydesktop Changing directory to .
2021-11-16 10:00:53 authydesktop App(s) found: 
2021-11-16 10:00:53 authydesktop could not find Authy Desktop.app
2021-11-16 10:00:53 authydesktop appversion: 
2021-11-16 10:00:53 authydesktop Latest version of Authy Desktop is 1.9.0
2021-11-16 10:00:53 authydesktop Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg
2021-11-16 10:00:53 authydesktop error downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy
2021-11-16 10:00:53 authydesktop DEBUG mode, not reopening anything
2021-11-16 10:00:53 authydesktop ################## End Installomator, exit code 2 
```

```
+./Installomator.sh:2> label='' 
+./Installomator.sh:19> export PATH=/usr/bin:/bin:/usr/sbin:/sbin
+./Installomator.sh:26> DEBUG=1 
+./Installomator.sh:29> NOTIFY=success 
+./Installomator.sh:37> BLOCKING_PROCESS_ACTION=tell_user 
+./Installomator.sh:67> LOGO=appstore 
+./Installomator.sh:80> IGNORE_APP_STORE_APPS=no 
+./Installomator.sh:91> INSTALL='' 
+./Installomator.sh:99> REOPEN=yes 
+./Installomator.sh:206> VERSION=0.8.0 
+./Installomator.sh:207> VERSIONDATE=2021-11-16 
+./Installomator.sh:272> log_location=/private/var/log/Installomator.log 
+./Installomator.sh:829> autoload is-at-least
+./Installomator.sh:831> sw_vers -productVersion
+./Installomator.sh:831> is-at-least 10.14 11.6.1
+is-at-least:23> emulate -L zsh
+is-at-least:25> local IFS=.- min_cnt=0 ver_cnt=0 part min_ver version order
+is-at-least:27> min_ver=( 10 14 ) 
+is-at-least:28> version=( 11 6 1 0 ) 
+is-at-least:30> ((  0 <= 2  ))
+is-at-least:31> [[ '' != <-> ]]
+is-at-least:32> ((  ++ver_cnt > 4  ))
+is-at-least:33> [[ 11 = *[0-9][^0-9]* ]]
+is-at-least:45> part=11 
+is-at-least:31> [[ 11 != <-> ]]
+is-at-least:48> true
+is-at-least:49> ((  ++min_cnt > 2  ))
+is-at-least:50> [[ 10 = <-> ]]
+is-at-least:50> break
+is-at-least:53> ((  part > min_ver[min_cnt]  ))
+is-at-least:53> return 0
+./Installomator.sh:837> [[ 1 -eq 0 ]]
+./Installomator.sh:844> [[ authydesktop == / ]]
+./Installomator.sh:850> [[ -n authydesktop ]]
+./Installomator.sh:851> [[ $1 -regex-match ".*\=.*" ]]
+./Installomator.sh:857> label=authydesktop 
+./Installomator.sh:860> shift 1
+./Installomator.sh:850> [[ -n '' ]]
+./Installomator.sh:864> label=authydesktop 
+./Installomator.sh:866> printlog '################## Start Installomator v. 0.8.0'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:58' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:58' authydesktop '################## Start Installomator v. 0.8.0'
2021-11-16 10:03:58 authydesktop ################## Start Installomator v. 0.8.0
+./Installomator.sh:867> printlog '################## authydesktop'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:58' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:58' authydesktop '################## authydesktop'
2021-11-16 10:03:58 authydesktop ################## authydesktop
+./Installomator.sh:871> versionKey=CFBundleShortVersionString 
+./Installomator.sh:874> currentUser=+./Installomator.sh:874> currentUser=+./Installomator.sh:874> awk '/Name :/ { print $3 }'
+./Installomator.sh:874> scutil
+./Installomator.sh:874> currentUser=username 
+./Installomator.sh:878> case authydesktop (version)
+./Installomator.sh:878> case authydesktop (longversion)
+./Installomator.sh:878> case authydesktop (valuesfromarguments)
+./Installomator.sh:878> case authydesktop (1password7)
+./Installomator.sh:878> case authydesktop (4kvideodownloader)
+./Installomator.sh:878> case authydesktop (8x8)
+./Installomator.sh:878> case authydesktop (abstract)
+./Installomator.sh:878> case authydesktop (adobebrackets)
+./Installomator.sh:878> case authydesktop (adobeconnect)
+./Installomator.sh:878> case authydesktop (adobereaderdc-update)
+./Installomator.sh:878> case authydesktop (adobereaderdc | adobereaderdc-install)
+./Installomator.sh:878> case authydesktop (aircall)
+./Installomator.sh:878> case authydesktop (airserver)
+./Installomator.sh:878> case authydesktop (airtame)
+./Installomator.sh:878> case authydesktop (aldente)
+./Installomator.sh:878> case authydesktop (alfred)
+./Installomator.sh:878> case authydesktop (alttab)
+./Installomator.sh:878> case authydesktop (amazonchime)
+./Installomator.sh:878> case authydesktop (amazonworkspaces)
+./Installomator.sh:878> case authydesktop (androidfiletransfer)
+./Installomator.sh:878> case authydesktop (anydesk)
+./Installomator.sh:878> case authydesktop (apparency)
+./Installomator.sh:878> case authydesktop (appcleaner)
+./Installomator.sh:878> case authydesktop (applenyfonts)
+./Installomator.sh:878> case authydesktop (applesfcompact)
+./Installomator.sh:878> case authydesktop (applesfmono)
+./Installomator.sh:878> case authydesktop (applesfpro)
+./Installomator.sh:878> case authydesktop (applesfsymbols | sfsymbols)
+./Installomator.sh:878> case authydesktop (aquaskk)
+./Installomator.sh:878> case authydesktop (arq7)
+./Installomator.sh:878> case authydesktop (asana)
+./Installomator.sh:878> case authydesktop (atext)
+./Installomator.sh:878> case authydesktop (atom)
+./Installomator.sh:878> case authydesktop (audacity)
+./Installomator.sh:878> case authydesktop (authydesktop)
+./Installomator.sh:1150> name='Authy Desktop' 
+./Installomator.sh:1151> type=dmg 
+./Installomator.sh:1152> downloadURL='https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy' 
+./Installomator.sh:1153> appNewVersion=+./Installomator.sh:1153> curl -sfL --output /dev/null -r 0-0 'https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy' --remote-header-name --remote-name -w '%{url_effective}\n'
+./Installomator.sh:1153> appNewVersion=+./Installomator.sh:1153> grep -o -E '([a-zA-Z0-9\_.%-]*)\.(dmg|pkg|zip|tbz)$'
+./Installomator.sh:1153> appNewVersion=+./Installomator.sh:1153> sed -E 's/.*-([0-9.]*)\.dmg/\1/g'
+./Installomator.sh:1153> appNewVersion=1.9.0 
+./Installomator.sh:1154> expectedTeamID=9EVH78F4V4 
+./Installomator.sh:3777> printlog 'BLOCKING_PROCESS_ACTION=tell_user'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'BLOCKING_PROCESS_ACTION=tell_user'
2021-11-16 10:03:59 authydesktop BLOCKING_PROCESS_ACTION=tell_user
+./Installomator.sh:3778> printlog 'NOTIFY=success'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'NOTIFY=success'
2021-11-16 10:03:59 authydesktop NOTIFY=success
+./Installomator.sh:3781> case appstore (appstore)
+./Installomator.sh:3784> [[+./Installomator.sh:3784> sw_vers -buildVersion
+./Installomator.sh:3784> [[ 20G224 > 19 ]]
+./Installomator.sh:3785> LOGO='/System/Applications/App Store.app/Contents/Resources/AppIcon.icns' 
+./Installomator.sh:3807> [[ ! -a '/System/Applications/App Store.app/Contents/Resources/AppIcon.icns' ]]
+./Installomator.sh:3814> printlog 'LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns'
2021-11-16 10:03:59 authydesktop LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
+./Installomator.sh:3817> [ -z '' ']'
+./Installomator.sh:3818> case dmg (dmg)
+./Installomator.sh:3820> archiveName='Authy Desktop.dmg' 
+./Installomator.sh:3837> [ -z '' ']'
+./Installomator.sh:3839> appName='Authy Desktop.app' 
+./Installomator.sh:3842> [ -z '' ']'
+./Installomator.sh:3843> case dmg (dmg)
+./Installomator.sh:3845> targetDir=/Applications 
+./Installomator.sh:3859> [[ -z '' ]]
+./Installomator.sh:3860> printlog 'no blocking processes defined, using Authy Desktop as default'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'no blocking processes defined, using Authy Desktop as default'
2021-11-16 10:03:59 authydesktop no blocking processes defined, using Authy Desktop as default
+./Installomator.sh:3861> blockingProcesses=( 'Authy Desktop' ) 
+./Installomator.sh:3865> [ 1 -ne 0 ']'
+./Installomator.sh:3867> tmpDir=+./Installomator.sh:3867> dirname ./Installomator.sh
+./Installomator.sh:3867> tmpDir=. 
+./Installomator.sh:3874> printlog 'Changing directory to .'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'Changing directory to .'
2021-11-16 10:03:59 authydesktop Changing directory to .
+./Installomator.sh:3875> cd .
+./Installomator.sh:3881> getAppVersion
+getAppVersion:4> type appCustomVersion
+getAppVersion:4> grep -q function
+getAppVersion:11> [[ '' !=  ]]
+getAppVersion:22> [[ -d '/Applications/Authy Desktop.app' ]]
+getAppVersion:24> [[ -d '/Applications/Utilities/Authy Desktop.app' ]]
+getAppVersion:27> applist=+getAppVersion:27> mdfind 'kind:application Authy Desktop.app' -0
+getAppVersion:27> applist='' 
+getAppVersion:29> printlog 'App(s) found: '
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'App(s) found: '
2021-11-16 10:03:59 authydesktop App(s) found: 
+getAppVersion:31> appPathArray=( ) 
+getAppVersion:33> [[ 0 -gt 0 ]]
+getAppVersion:54> printlog 'could not find Authy Desktop.app'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'could not find Authy Desktop.app'
2021-11-16 10:03:59 authydesktop could not find Authy Desktop.app
+./Installomator.sh:3882> printlog 'appversion: '
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'appversion: '
2021-11-16 10:03:59 authydesktop appversion: 
+./Installomator.sh:3886> [[ -n 1.9.0 ]]
+./Installomator.sh:3887> printlog 'Latest version of Authy Desktop is 1.9.0'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'Latest version of Authy Desktop is 1.9.0'
2021-11-16 10:03:59 authydesktop Latest version of Authy Desktop is 1.9.0
+./Installomator.sh:3888> [[ '' == 1.9.0 ]]
+./Installomator.sh:3915> [[ -n '' || dmg == updateronly ]]
+./Installomator.sh:3931> [ -f 'Authy Desktop.dmg' ']'
+./Installomator.sh:3935> printlog 'Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:03:59' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:03:59' authydesktop 'Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg'
2021-11-16 10:03:59 authydesktop Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg
+./Installomator.sh:3936> [[ username != loginwindow && success == all ]]
+./Installomator.sh:3940> curl --location --fail --silent 'https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy' -o 'Authy Desktop.dmg'
+./Installomator.sh:3941> printlog 'error downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:04:00' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:04:00' authydesktop 'error downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy'
2021-11-16 10:04:00 authydesktop error downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy
+./Installomator.sh:3942> message='Authy Desktop update/installation failed. This will be logged, so IT can follow up.' 
+./Installomator.sh:3943> [[ username != loginwindow && success == all ]]
+./Installomator.sh:3947> cleanupAndExit 2
+cleanupAndExit:1> [[ -n '' ]]
+cleanupAndExit:4> [ 1 -eq 0 ']'
+cleanupAndExit:10> [ -n '' ']'
+cleanupAndExit:16> reopenClosedProcess
+reopenClosedProcess:5> [[ yes != yes ]]
+reopenClosedProcess:11> [[ 1 -ne 0 ]]
+reopenClosedProcess:12> printlog 'DEBUG mode, not reopening anything'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:04:00' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:04:00' authydesktop 'DEBUG mode, not reopening anything'
2021-11-16 10:04:00 authydesktop DEBUG mode, not reopening anything
+reopenClosedProcess:13> return
+cleanupAndExit:17> printlog '################## End Installomator, exit code 2 \n\n'
+printlog:2> timestamp=+printlog:2> date '+%F %T'
+printlog:2> timestamp='2021-11-16 10:04:00' 
+printlog:4> [[+printlog:4> whoami
+printlog:4> [[ username == root ]]
+printlog:7> echo '2021-11-16 10:04:00' authydesktop '################## End Installomator, exit code 2 \n\n'
2021-11-16 10:04:00 authydesktop ################## End Installomator, exit code 2 


+cleanupAndExit:18> exit 2
```

It looks like curl is still failing to download the file now with a 505 HTTP Version not supported error being returned. I think this is due to their being a space in the quoted URL that gets returned & followed, currently: `https://s3.amazonaws.com/authy-electron-repository-production/authy/stable/1.9.0/darwin/x64/Authy Desktop-1.9.0.dmg`. I had to modify this to `https://s3.amazonaws.com/authy-electron-repository-production/authy/stable/1.9.0/darwin/x64/Authy%20Desktop-1.9.0.dmg` to get curl to successfully download it.

**Comment by Theile** [comment]
I don't know what is wrong in you setup. As you can see from my log output, it works fine. I can also use the URL in Safari.

**Comment by fleish** [comment]
I'm not sure why it's behaving differently either. I've tried running this on my main rig & a fresh Big Sur VM that is only used for testing and lacks anything I would suspect to be getting in the way of this. I'm just following what the script is doing minus the fail option in order to surface the error it is encountering.

**Comment by Theile** [comment]
You have debug on, does the script have writing permissions?

**Comment by adibue** [comment]
Hey guys. I just observed exactly the same issue (running via Jamf Pro):

```
$ sudo jamf policy -verbose
 verbose: JAMF binary already symlinked
 verbose: Checking for an existing instance of this application...
Checking for policies triggered by "recurring check-in" for user "buehler"...
 verbose: Checking for active ethernet connection...
 verbose: No active ethernet connection found...
 verbose: Removing any cached policies for this trigger.
 verbose: Parsing servers...
 verbose: Parsing Policy Authy updated (400)...
 verbose: The Management Framework Settings are up to date.
 verbose: Found 1 matching policies.
Executing Policy Authy updated
 verbose: Copying script to temp directory...
 verbose: Determining script type...
Running script Installomator.zsh...
Script exit code: 2
Script result: 2021-11-17 16:37:34  shifting arguments for Jamf
2021-11-17 16:37:34 authydesktop setting variable from argument DEBUG=0
2021-11-17 16:37:34 authydesktop setting variable from argument LOGO="/usr/local/SWITCH/resources/foldericons/kiosk.icns"
2021-11-17 16:37:34 authydesktop setting variable from argument NOTIFY=success
2021-11-17 16:37:34 authydesktop setting variable from argument BLOCKING_PROCESS_ACTION=prompt_user
2021-11-17 16:37:34 authydesktop ################## Start Installomator v. 0.8.0
2021-11-17 16:37:34 authydesktop ################## authydesktop
2021-11-17 16:37:35 authydesktop BLOCKING_PROCESS_ACTION=prompt_user
2021-11-17 16:37:35 authydesktop NOTIFY=success
2021-11-17 16:37:35 authydesktop LOGO=/usr/local/SWITCH/resources/foldericons/kiosk.icns
2021-11-17 16:37:35 authydesktop no blocking processes defined, using Authy Desktop as default
2021-11-17 16:37:35 authydesktop Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.biGNVfpW
2021-11-17 16:37:35 authydesktop App(s) found: /Applications/Authy Desktop.app
2021-11-17 16:37:35 authydesktop found app at /Applications/Authy Desktop.app, version 1.8.4
2021-11-17 16:37:35 authydesktop appversion: 1.8.4
2021-11-17 16:37:35 authydesktop Latest version of Authy Desktop is 1.9.0
2021-11-17 16:37:35 authydesktop Downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy to Authy Desktop.dmg
2021-11-17 16:37:36 authydesktop error downloading https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy
2021-11-17 16:37:36 authydesktop Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.biGNVfpW
2021-11-17 16:37:36 authydesktop App not closed, so no reopen.
2021-11-17 16:37:36 authydesktop ################## End Installomator, exit code 2
```

**Comment by fleish** [comment]
@Theile yes, the user has write permissions. Can you run these commands on your system to maybe sort out the differences?

Download: `curl --location --fail --silent 'https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy' -o 'Authy Desktop.dmg'`

Verify it was downloaded: `file 'Authy Desktop.dmg' - which should return either `Authy Desktop.dmg: zlib compressed data` or `Authy Desktop.dmg: cannot open `Authy Desktop.dmg' (No such file or directory)`

Check the default version of curl for your PATH: `which curl`

Verify the version of curl: `curl --version`

You can also check for other versions of curl you have installed: `whereis curl`

I find this does **NOT** work with the version of curl included with macOS @ `/usr/bin/curl`

Catalina:
```
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

Big Sur:
```
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```
 
However, I find it **DOES** work with a version I have from MacPorts:
```
curl 7.68.0 (x86_64-apple-darwin18.7.0) libcurl/7.68.0 OpenSSL/1.1.1h zlib/1.2.11 libidn2/2.3.1 libpsl/0.21.0 (+libidn2/2.1.1)
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP UnixSockets
```

I'm wondering if something about your environment is finding a different version of curl that is causing it to work for you but not others who just have the stock version from macOS.

**Comment by Theile** [comment]
I'm on Monterey on a M1, maybe that version is newer. I reopened this issue, hopefully we can make a fix for this soon.

**Comment by fleish** [comment]
Indeed, Monterey seems to be in between BigSur and my macports version:

```
curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

**Comment by Theile** [comment]
Yes, same on my M1. It's a server-problem, mostly. Not sure we can do any kinds of workarounds, just for one label, but I leave this open, so you are welcome to seek help on Slack or something.

**Comment by Theile** [comment]
So a thought came to my mind, maybe the issue can be solved with extra headers in the `curl` command on Catalina.

I have a PR with `curlOptions` variable that can be used for various extra headeres needed for the software to download: [PR 369](https://github.com/Installomator/Installomator/pull/369)

The labels beginning with "mocha" on that PR show some headers that can be used, but if the download is inspected in a Browser (Safari with Developer menu) the headers used there can also be seen.

**Comment by fleish** [comment]
Interesting idea. I couldn't come up with any headers that would force curl workaround this issue but I did think of a way to "fix" the URL so the included space is properly encoded. The below calls the initial URL without following it or displaying the response outside of the redirect_url and then replaces any spaces found with `%20` so they are properly urlencoded:
`downloadURL=$(/usr/bin/curl -s -w '%{redirect_url}' -o /dev/null "https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy" | sed 's/\ /%20/g')
`

Submitted pull request https://github.com/Installomator/Installomator/pull/380

**Comment by Theile** [comment]
Great investigation, thank you! 
Corrected here: [PR 382](https://github.com/Installomator/Installomator/pull/382)
